FROM python:3 


WORKDIR /prod/client

# Installe les libs système nécessaires à OpenCV
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Installe le reste 
COPY prod/client/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY prod/client/ .

# Lance le Bash
CMD ["bash", "start_client.sh"]
